# DockerFile will follow OpenContainer standards: https://github.com/opencontainers/image-spec/blob/main/annotations.md

# Instruct source image to use
FROM alpine

LABEL org.opencontainers.image.authors="Mick McCarthy <email@address.com>" \
      org.opencontainers.image.description="Container image for https://github.com/abishekvashok/cmatrix"

WORKDIR cmatrix

RUN apk update && \
    apk add git autoconf automake alpine-sdk ncurses-dev ncurses-static && \
    git clone https://github.com/spurin/cmatrix.git . && \
    autoreconf -i && \
    mkdir -p /usr/lib/kbd/consolefonts /usr/share/consolefonts && \
    ./configure LDFLAGS="-static" && \
    make

CMD ["./cmatrix"]
