# DockerFile will follow OpenContainer standards: https://github.com/opencontainers/image-spec/blob/main/annotations.md

# Instruct source image to use
FROM alpine

LABEL org.opencontainers.image.authors="Mick McCarthy <email@address.com>"
LABEL org.opencontainers.image.description="Container image for https://github.com/abishekvashok/cmatrix"


